# Generated by Django 5.2.5 on 2025-09-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0003_remove_rayon_produit_contenir_produit_rayons_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='dateFabrication',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
