# Generated by Django 5.2.5 on 2025-09-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0004_produit_datefabrication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('idStatus', models.AutoField(primary_key=True, serialize=False)),
                ('lbStatus', models.CharField(max_length=100)),
            ],
        ),
    ]
