# Generated by Django 5.2.5 on 2025-09-16 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0006_produit_status_alter_produit_categorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='dateFabrication',
        ),
        migrations.AddField(
            model_name='produit',
            name='dateFabProd',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
