# Generated by Django 4.2.24 on 2025-10-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0007_remove_produit_datefabrication_produit_datefabprod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenir',
            name='Qte',
            field=models.IntegerField(default=1),
        ),
    ]
